version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: barber_postgres
    environment:
      POSTGRES_DB: barber_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - barber_network

  redis:
    image: redis:7-alpine
    container_name: barber_redis
    ports:
      - "6379:6379"
    networks:
      - barber_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: barber_backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/barber_app
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      PORT: 3001
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - barber_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: barber_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_APP_URL: http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - barber_network

volumes:
  postgres_data:

networks:
  barber_network:
    driver: bridge